### ISSUE TITLE
web-1.2 crashes

### ISSUE THREAD

**Issue by Murf** [sixeyed/docker-windows-workshop#3]
[ArgumentNullException: Value cannot be null.
Parameter name: String]
   System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) +223
   System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) +180
   SignUp.Model.SignUpConfiguration..ctor() in C:\src\SignUp.Model\ProductLaunchConfiguration.cs:11

**Comment by sixeyed** [comment]
Must have fixed this with a previous commit without realising :)
