### ISSUE TITLE
SqlPackage.exe is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by eaitbrahim** [sixeyed/docker-windows-workshop#8]
docker container logs signup-db

VERBOSE: Starting SQL Server
VERBOSE: Changing SA login credentials
VERBOSE: No data files - will create new database
& : The term 'C:\Program Files (x86)\Microsoft SQL
Server\130\DAC\bin\SqlPackage.exe' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At C:\init\Initialize-Database.ps1:37 char:3
+ & $SqlPackagePath  `
+   ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\SqlPackage.e
   xe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Invoke-Sqlcmd : Could not find file 'C:\init\deploy.sql'.
At C:\init\Initialize-Database.ps1:43 char:1
+ Invoke-Sqlcmd -InputFile deploy.sql -Variable $SqlCmdVars -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Invoke-Sqlcmd], FileNotFound
   Exception
    + FullyQualifiedErrorId : ExecutionFailed,Microsoft.SqlServer.Management.P
   owerShell.GetScriptCommand

VERBOSE: Deployed SignUp database, data files at: C:\data

**Comment by sixeyed** [comment]
Content has moved on :)
